### PR TITLE
Should now be able to use Material Design Icon font.

### PR DESCRIPTION
**Pull request by maneex**
This PR should allow to properly use Material Design Icon font (https://materialdesignicons.com/) with Prawn-icon.

Resolves: #58

### CODE REVIEW

**Comment by jessedoyle** [comment]
Hey @maneex - thanks so much for the contribution! This looks great!

I'm going to push a commit or two to your branch to touch up a few minor things, but ultimately this is awesome - thanks again!

**Review by jessedoyle — APPROVED** [review]
Awesome, thanks so much for the contribution! There's a few non-related items that I'm hoping to merge in, then cut a new release!

The next release should be version `3.1.0`. Thanks again!

**Review by jessedoyle — APPROVED** [review]
Sorry for the force push - just bring the branch up to date with master!

**Comment by jessedoyle** [comment]
@maneex - I've published version [3.1.0](https://rubygems.org/gems/prawn-icon/versions/3.1.0) to RubyGems that includes this change.

Thanks again!

**Comment by markcraig** [comment]
Thank you for this @maneex

**Pull request merged**
